### PR TITLE
Use parseString() API instead of internal Parser.

### PR DESCRIPTION
**Pull request by scheglov**

### CODE REVIEW

**Comment by kevmoo** [comment]
@scheglov – if you rebase on top of @natebosch pending PR, travis should be happier

**Comment by kevmoo** [comment]
@scheglov – have you looked at the pkg:analyzer dependency? Does that need to be changed?

**Comment by scheglov** [comment]
@kevmoo Yes, rebasing helped.

`parseString` was added in https://dart-review.googlesource.com/c/sdk/+/105540, `Jun 12, 2019`, before the version [0.38.3](https://pub.dev/packages/analyzer/versions/0.38.3).

**Comment by scheglov** [comment]
Yes, it would be nice to get it pulled into SDK.
Not burning though, so can be done any time.

**Pull request merged**
