### PR TITLE
Implement visitor method to be added in the analyzer package

### PR DESCRIPTION
**Pull request by bwilkerson**
We'll want to add a type for the parameter and remove the explicit type on the list literal after updating the dependency constraints.

### CODE REVIEW

**Comment by bwilkerson** [comment]
@munificent

**Comment by munificent** [comment]
Can you revert the change that reorders all the members? That's not exactly diff friendly.

**Comment by bwilkerson** [comment]
Sorry about that! Sorting changes reverted.

**Comment by munificent** [comment]
Thanks!

**Pull request merged**
