### PR TITLE
Republish dart_style 2.0.3 as 2.1.1.

### LINKED ISSUE #1051: Error: 'FunctionReference' isn't a type
The upgrade from 2.0.3 to 2.1.0 throws an error when running build_runner

`$ flutter packages pub run build_runner build --delete-conflicting-outputs`

```
Failed to precompile build_runner:build_runner:
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-2.1.0/lib/src/source_visitor.dart:1809:31: Error: Type 'FunctionReference' not found.
  void visitFunctionReference(FunctionReference node) {
                              ^^^^^^^^^^^^^^^^^
../../snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-2.1.0/lib/src/source_visitor.dart:1809:31: Error: 'FunctionReference' isn't a type.
  void visitFunctionReference(FunctionReference node) {
                              ^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by munificent**
This enables pub to avoid selecting 2.1.0, which has a bad constraint
on analyzer.

Fix #1051.

### CODE REVIEW

**Comment by natebosch** [comment]
Do you plan to publish from this commit and then do a merge commit into master to resolve the conflicts?

**Review by natebosch — APPROVED** [review]

**Comment by munificent** [comment]
I updated the CHANGELOG so that it's continuous. I'm not planning to merge this back into master.

**Comment by natebosch** [comment]
> I'm not planning to merge this back into master. I'll just tag this branch and publish it.

We prefer that all published commits are on the main branch. @kevmoo @jakemac53 - did we ever have this documented anywhere?

**Comment by munificent** [comment]
Abandoning in favor of #1058.

**Pull request closed without merging**
