### PR TITLE
Regression test for #901.

### LINKED ISSUE #901: Line Separator U+2028 in comment fails to format entire file
Got a dart file with a Line Separator character U+2028 (hex: E2 80 A8) in a comment (copy and pasted extra text from a web page).

`dartfmt input.dart` fails with:

```
The formatter produced unexpected output. Input was:
... source file
Which formatted to:
... correctly formatted file with removed Line Separator
Please report at github.com/dart-lang/dart_style/issues.
```

`flutter format input.dart` fails with the same as `dartfmt` above, but with the added:

```
Formatting failed: 65
```

It would be nice if it points which line/character the unexpected output starts/ends.

### PR DESCRIPTION
**Pull request by munificent**
Close #901.

### CODE REVIEW

**Comment by munificent** [comment]
Ah, wait. Don't review this yet. I just realized that I can repro this if the line separator is at the *end* of a line.

**Comment by natebosch** [comment]
Is there any change worth landing here?

**Comment by lrhn** [comment]
Seems the issue was fixed in #944.

**Comment by kevmoo** [comment]
???

**Pull request closed without merging**
