### PR TITLE
no extra-indent of expression function as argument with trailing comma

### PR DESCRIPTION
**Pull request by a14n**
Actual:

```dart
      onTap: () {
        Navigator.of(context).push(CupertinoPageRoute<void>(
          title: colorName,
          builder: (BuildContext context) => Tab1ItemPage(
                color: color,
                colorName: colorName,
                index: index,
              ),
        ));
      },
```

Expected:

```dart
      onTap: () {
        Navigator.of(context).push(CupertinoPageRoute<void>(
          title: colorName,
          builder: (BuildContext context) => Tab1ItemPage(
            color: color,
            colorName: colorName,
            index: index,
          ),
        ));
      },
```

### CODE REVIEW

**Comment by kevmoo** [comment]
I *think* this is by design. @munificent will have thoughts

**Comment by a14n** [comment]
>I think this is by design.

As this looks similar to #382 (that is not closed) this change seems doable.

(Context: I try to apply `dartfmt` on `flutter/examples` and see what's the smallest set of changes to be done to use it (or a small customized version) on flutter examples. Ideally those changes should be part of the current dartfmt to limit divergencies)

**Comment by a14n** [comment]
The same behaviour could be done on function declarations and method declarations (I did it in https://github.com/a14n/dart_style/commit/7a51442c63fdd269b7421e0073256b3ab3ae4706 - happy to include it in this PR).

**Comment by munificent** [comment]
I'm a little swamped with other stuff to take a look at these right now, but I'll try to circle back when I can.

I have some vague concerns that this will do bad things on more complex cases, so I'll need to run it on a bigger corpus and see what the results look like. The output you have here looks nice to me. It's mostly a question of making sure it doesn't regress other things.

**Comment by a14n** [comment]
The only concern I have is when the function split after `=>`:

```dart
    onTap: () {
      Navigator.of(context).push(CupertinoPageRoute<void>(
        title: colorName,
        builder_______________________________________________: (BuildContext context) =>
            Tab1ItemPage(
          color: color,
          colorName: colorName,
          index: index,
        ),
      ));
    },
```

Ideally in this case I'd like to have:

```dart
    onTap: () {
      Navigator.of(context).push(CupertinoPageRoute<void>(
        title: colorName,
        builder_______________________________________________: (BuildContext context) =>
            Tab1ItemPage(
              color: color,
              colorName: colorName,
              index: index,
            ),
      ));
    },
```

But I don't manage to write the good code to handle this case and to produce what I'd like :-(

**Comment by kasperpeulen** [comment]
I think best would be this:

```dart
    onTap: () {
      Navigator.of(context).push(CupertinoPageRoute<void>(
        title: colorName,
        builder_______________________________________________: (BuildContext context) =>
          Tab1ItemPage(
            color: color,
            colorName: colorName,
            index: index,
          ),
      ));
    },
```

**Comment by a14n** [comment]
@munificent friendly reminder

**Comment by munificent** [comment]
I tested this out on a big corpus locally. Overall, I like the output. However, like you note, the results are pretty weird when it needs to indent before the body of the function, as in:

```dart
  function(
    (parameter1, parameter2,
            parameter3) =>
        P(
      p,
    ),
  );
```

Cases like this seem pretty rare in the wild though, so I think it's still worth doing.

**Pull request merged**
