### PR TITLE
Enable support for inline class syntax

### LINKED ISSUE #1129: [Extension type] dart_style support

### PR DESCRIPTION
**Pull request by mraleph**
Quick and dirty draft of the support. Currently we can't access `inlineToken` because public AST API does not expose it. 

We need [this CL](https://dart-review.googlesource.com/c/sdk/+/286180) to land first and then publish analyzer. Once that happens I will bump analyzer version in pubspec and convert this draft PR into a proper PR. 

/cc @munificent 

Fixes #1129

### CODE REVIEW

**Comment by munificent** [comment]
I usually wait until there is public analyzer AST support for new syntax before I add formatting support. Is it OK if we wait until the analyzer folks have published a version before we land this?

**Comment by mraleph** [comment]
Yep, that's why it is draft :) The CL has landed and I am going to ask analyzer to be published next.

**Comment by mraleph** [comment]
And we are ready to go.

**Comment by mraleph** [comment]
Analyzer started using methods from 2.19 so we need to bump the action to use 2.19.

**Comment by mraleph** [comment]
Now everything cycles green.

**Comment by mraleph** [comment]
friendly ping @munificent

**Comment by mraleph** [comment]
Fixed conflicts in CHANGELOG.md. Still waiting for review.

**Review by munificent — APPROVED** [review]

**Pull request merged**
